language: go
sudo: false
env:
  global:
  - BINARY_NAME=aws-env
matrix:
  include:
  - os: linux
    go: 1.13.x
    env:
    - TARGET=darwin
    - ARCH=amd64
  - os: linux
    go: 1.13.x
    env:
    - TARGET=linux
    - ARCH=amd64
  - os: linux
    go: 1.13.x
    env:
    - TARGET=windows
    - ARCH=amd64
    - EXT=.exe
notifications:
  email: false
script:
- make release
deploy:
  provider: releases
  api_key:
    secure: QRRFMG+RM0ev9oyNxIsmITDOITvAkBp4U1JjNXEuqhsqAB5IfSvYQeIKlPlQi4TeCAJ/Wetv15LGwB3C8MslvX+KOOumOS5MsI0aDm0WlrCM1A3lqGaV9efAjv4vIci61dhSb1awwXNCZhwEfTso7xKJQh26PBIJ7Y6sTi4Yvq3eUWY7+L5eCY9nHgqN9aDFKj+QhN99Pr/OKmfF/IItxH2h4UdlZB3jaJmhHVzRLOCeJhYUliQRHFebcenE4RHtz6IPrlLD+7arLG15oTRZ4tUJoxnfRnQ9WBWv0PC/jB7Zs4/pQcwxTjivoJsJRVkUW2fAOZrQ6vGyMJ8MnH0Z8+U/6TdAXzKDI2GbvJg+SooFER1pMA/Ci/Ceg+PEHlLbpXLOpvkc0l+h/AvqJ3Q0ZYSQM/tCbiWoBdhHCQyPRqUDfW9TUZE+dlHypq/M4eJNd5GhV3lwIV0i8+jrnj2TbNcxgLRbGSuAS5DcPB6j4e0i8LbMSwom6JUECenqTL51ANdVqyJgwEhWuOtaEJgnZwGlh4m05yhWHeX5+8IJT8cSL8Xdrf210jCwLGg9diwdXA+LyDEeRjxY/FwNAmI7pqO8Ws7vhvfV349Ok6Sm+dVGagJrT+NQlG82NmZTlcFxshH/csCZDlN1+6y5pGxhsp1P+Fa/ukb/KUgXN8ojIwg=
  file: "${BINARY_NAME}-${TARGET}-${ARCH}${EXT}"
  skip_cleanup: true
  on:
    repo: telia-oss/aws-env
    tags: true
